# Generated by Django 5.1 on 2024-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('cast', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movie_images/')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
            ],
        ),
    ]
